# Generated by Django 4.2.3 on 2023-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_access',
            field=models.BooleanField(default=False),
        ),
    ]
